name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: Deploy to NuxtHub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      # Cache skew-protection AFTER install, BEFORE build
      - name: Cache skew-protection
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/nuxt/skew-protection
          key: skew-protection-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            skew-protection-${{ github.ref_name }}-
            skew-protection-

      - name: Build & Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          project-key: nuxtseo-com-rtoh
        env:
          NODE_OPTIONS: "--max-old-space-size=12288"
